[Book]
author = ["Kirjailija", "True"]
title = ["Kirjan nimi", "True"]
year = ["Kirjan julkaisuvuosi", "True"]
publisher = ["Kirjan julkaisija", "True"]
[Article]
author  = ["Artikkelin tekij√§(t)", "True"]
title   = ["Artikkelin nimi", "True"]
journal = ["Aikakausjulkaisu", "True"]
year    = ["Artikkelin julkaisuvuosi", "True"]
volume  = ["Nidos",""]
number  = ["Luku",""]
pages   = ["Sivut",""]
month   = ["Kuukausi",""]
note    = ["Nootti",""]
annote  = ["Huomautus",""]
[Misc]
title = ["Title", "True"]
author = ["Kirjailija", "True"]
howpublished = ["Julkaistu", "True"]
year = ["Vuosi", "True"]
note = ["Note", "True"]
